if setfflag then
	setfflag("CrashUploadToBacktraceUrl", "")
	setfflag("CrashpadUploadToBacktraceUrl", "")
	setfflag("CrashUploadToBacktracePercentage", 0)
	setfflag("CrashUploadToBacktraceWindowsPlayerToken", "")
	setfflag("CrashUploadToBacktraceBlackholeToken", "")
	setfflag("DebugCrashEnabled", "False")
	setfflag("GoogleAnalyticsAccountPropertyID", "")
	setfflag("WindowsLaunchTypeAnalytics", "False")
	setfflag("AbuseReportScreenshot", "False")
	setfflag("AbuseReportScreenshotPercentage", 0)
	setfflag("TelegrafHTTPTransportUrl", "")
	setfflag("EnableGCapsHardwareTelemetry", "False")
	setfflag("EnableExtendedHardwareTelemetry", "False")
	setfflag("EnableInferredOOMTelemetry", "False")
	setfflag("EnableHardwareTelemetry", "False")
	setfflag("HardwareTelemetryHundredthsPercent", 0)
end
